apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthcare-app-test
  labels:
    app: healthcare
    env: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: healthcare
      env: test
  template:
    metadata:
      labels:
        app: healthcare
        env: test
    spec:
      containers:
        - name: healthcare-container
          image: akku/healthcare:test
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "256Mi"
              cpu: "300m"
            requests:
              memory: "128Mi"
              cpu: "150m"
