apiVersion: apps/v1
kind: Deployment
metadata:
  name: medicure-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: medicure
  template:
    metadata:
      labels:
        app: medicure
    spec:
      containers:
        - name: medicure
          image: akku1999/medicure-app:v01
          ports:
            - containerPort: 8080
